# Generated by Django 5.1.1 on 2024-09-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="version",
            options={
                "verbose_name": "Версия продукта",
                "verbose_name_plural": "Версии продуктов",
            },
        ),
    ]
